source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.2'
use_frameworks!
target 'Unity-iPhone' do
pod 'Alamofire', '~> 4.5'
pod 'Firebase/Analytics', '4.0.4'
pod 'Firebase/Core', '4.0.4'
end
